/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.quest {
	import laya.ui.*;
	import laya.display.*;
	import script.Quest.QuestCtrl;
	import laya.display.Text;

	public class QusetSceneUI extends Scene {
		public var nextBtn:Button;
		public var backBtn:Button;
		public var soundList:List;
		public var selectList:List;
		public var timeBox:Sprite;
		public var timeLabel:Text;
		public var reStartBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("quest/QusetScene");

		}

	}
}