/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.demo {
	import laya.ui.*;
	import laya.display.*;
	import script.Quest.MainCtrl;
	import laya.display.Text;

	public class DemoSceneUI extends Scene {
		public var btnList:List;
		public var testTF:Box;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("demo/DemoScene");

		}

	}
}